function Myeloarchitectonicstable1 = importfile_table(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MYELOARCHITECTONICSTABLE1 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  MYELOARCHITECTONICSTABLE1 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2021-08-26 14:44:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Parcel_index", "Nieuwenhuys_parcel", "Lobe", "GLI_exist", "GLI_lateral", "GLI_superior", "GLI_median", "GLI_inferior", "GLI_Mean", "Depth_exist", "Baillarger_type", "Baillarger_type_detail", "Intrusion_type", "Density_type", "Reference", "Original_information_source", "Depth_profle"];
opts.VariableTypes = ["double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Nieuwenhuys_parcel", "Lobe", "Baillarger_type", "Baillarger_type_detail", "Intrusion_type", "Density_type", "Reference", "Original_information_source", "Depth_profle"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Nieuwenhuys_parcel", "Lobe", "Baillarger_type", "Baillarger_type_detail", "Intrusion_type", "Density_type", "Reference", "Original_information_source", "Depth_profle"], "EmptyFieldRule", "auto");

% Import the data
Myeloarchitectonicstable1 = readtable(filename, opts);

end